apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.microservice.name }}-{{ .Values.microservice.version }}
  labels:
    app: {{ .Values.microservice.name }}
    version: {{ .Values.microservice.version }}
spec:
  replicas: {{ .Values.microservice.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.microservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.microservice.name }}
        version: {{ .Values.microservice.version }}
    spec:
      serviceAccountName: {{ .Values.microservice.name }}
      containers:
        - name: {{ .Values.microservice.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--port", "{{ .Values.microservice.port }}"]
          ports:
          - name: http
            containerPort: {{ .Values.microservice.port }}
          {{- if .Values.env }}
          env:
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: "{{ $val }}"
          {{- end }}
          {{- end }}
