swagger: "2.0"
info:
  description: "This is the Transaction Microservice, responsible for managing Transactions in Modern Bank."
  version: "1.0.0"
  title: "Transaction"
host: "transactions"
basePath: "/v1"
tags:
- name: "transaction"
  description: "Operations about transactions"
schemes:
- "http"
definitions:
  Transaction:
    allOf:
      - $ref: "#/definitions/NewTransaction"
      - type: "object"
        required:
          - id
        properties:
          id:
            type: "string"
  NewTransaction:
    required:
      - sender
      - receiver
      - amount
    type: "object"
    properties:
      sender:
        type: "integer"
        format: "int64"
      receiver:
        type: "integer"
        format: "int64"
      amount:
        type: "number"
        format: "currency"
paths:
  /transactions:
    post:
      tags:
      - "transactions"
      summary: "Create a new transaction to an account"
      description: "Creates a new transaction in the log"
      operationId: "createTransaction"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created transaction"
        required: true
        schema:
          $ref: "#/definitions/NewTransaction"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/Transaction"
        500:
          description: "Internal server error"
  /account/{sender}/sent:
    get:
      tags:
      - "transactions"
      summary: "Lists all transactions sent from a given account"
      description: "Lists all transactions sent from a given account"
      operationId: "listTransactionsSent"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "sender"
        description: "Account number that made the transactions"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Success!"
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        404:
          description: "Account not found"
        500:
          description: "Internal server error"
  /account/{receiver}/received:
    get:
      tags:
      - "transactions"
      summary: "Lists all transactions sent to a given account"
      description: "Lists all transactions sent to a given account"
      operationId: "listTransactionsReceived"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "receiver"
        description: "Account number that received the transactions"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Success!"
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        404:
          description: "Account not found"
        500:
          description: "Internal server error"
  /account/{sender}/sent/{transaction}:
    get:
      tags:
      - "transactions"
      summary: "Get a specific transaction sent from a given account"
      description: "Get a specific transaction sent from a given account"
      operationId: "getTransactionSent"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "sender"
        description: "Account number that made the transactions"
        required: true
        type: "integer"
        format: "int64"
      - in: "path"
        name: "transaction"
        description: "Transaction ID"
        required: true
        type: "string"
      responses:
        200:
          description: "Success!"
          schema:
            $ref: "#/definitions/Transaction"
        404:
          description: "Transaction not found"
        500:
          description: "Internal server error"
  /account/{receiver}/received/{transaction}:
    get:
      tags:
      - "transactions"
      summary: "Get a specific transaction received by a given account"
      description: "Get a specific transaction received by a given account"
      operationId: "getTransactionReceived"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "receiver"
        description: "Account number that received the transactions"
        required: true
        type: "integer"
        format: "int64"
      - in: "path"
        name: "transaction"
        description: "Transaction ID"
        required: true
        type: "string"
      responses:
        200:
          description: "Success!"
          schema:
            $ref: "#/definitions/Transaction"
        404:
          description: "Transaction not found"
        500:
          description: "Internal server error"
