swagger: "2.0"
info:
  description: "This is the Payment Processing Microservice, ensuring transactions are processed in Modern Bank."
  version: "1.0.0"
  title: "PaymentProcessing"
host: "payment-processing"
basePath: "/v1"
tags:
- name: "paymentProcessing"
  description: "Operations about handling payments"
schemes:
- "http"
definitions:
  Payment:
    type: "object"
    required:
      - sender
      - receiver
      - amount
    properties:
      sender:
        description: "sending account number"
        type: "integer"
        format: "int64"
      receiver:
        description: "receiving account number"
        type: "integer"
        format: "int64"
      amount:
        description: "amount to send"
        type: "number"
        format: "currency"
paths:
  /payment:
    post:
      tags:
      - "paymentProcessing"
      summary: "Sends money from one account to another"
      description: "Sends money from one account to another"
      operationId: "makePayment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Payment to make"
        required: true
        schema:
          $ref: "#/definitions/Payment"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/Payment"
        500:
          description: "Internal server error"
