schemes:
- http
swagger: "2.0"
info:
  description: This is the Transaction Log Microservice, an immutable append-only
    Transaction Log in Modern Bank.
  title: Transaction Log
  version: 1.0.0
host: transaction-log
basePath: /v1
paths:
  /account/{receiver}/received:
    get:
      description: Lists all transactions sent to a given account
      produces:
      - application/json
      tags:
      - transactions
      summary: Lists all transactions sent to a given account
      operationId: listTransactionsReceived
      parameters:
      - type: integer
        format: int64
        description: Account number that received the transactions
        name: receiver
        in: path
        required: true
      responses:
        "200":
          description: Success!
          schema:
            allOf:
            - type: array
              items:
                $ref: '#/definitions/transaction'
            - $ref: '#/definitions/version'
        "404":
          description: No transactions found
        "500":
          description: Internal server error
  /account/{receiver}/received/{transaction}:
    get:
      description: Get a specific transaction received by a given account
      produces:
      - application/json
      tags:
      - transactions
      summary: Get a specific transaction received by a given account
      operationId: getTransactionReceived
      parameters:
      - type: integer
        format: int64
        description: Account number that received the transactions
        name: receiver
        in: path
        required: true
      - type: string
        description: Transaction ID
        name: transaction
        in: path
        required: true
      responses:
        "200":
          description: Success!
          schema:
            allOf:
            - $ref: '#/definitions/transaction'
            - $ref: '#/definitions/version'
        "404":
          description: Transaction not found
        "500":
          description: Internal server error
  /account/{sender}/sent:
    get:
      description: Lists all transactions sent from a given account
      produces:
      - application/json
      tags:
      - transactions
      summary: Lists all transactions sent from a given account
      operationId: listTransactionsSent
      parameters:
      - type: integer
        format: int64
        description: Account number that made the transactions
        name: sender
        in: path
        required: true
      responses:
        "200":
          description: Success!
          schema:
            allOf:
            - type: array
              items:
                $ref: '#/definitions/transaction'
            - $ref: '#/definitions/version'
        "404":
          description: No transactions found
        "500":
          description: Internal server error
  /account/{sender}/sent/{transaction}:
    get:
      description: Get a specific transaction sent from a given account
      produces:
      - application/json
      tags:
      - transactions
      summary: Get a specific transaction sent from a given account
      operationId: getTransactionSent
      parameters:
      - type: integer
        format: int64
        description: Account number that made the transactions
        name: sender
        in: path
        required: true
      - type: string
        description: Transaction ID
        name: transaction
        in: path
        required: true
      responses:
        "200":
          description: Success!
          schema:
            allOf:
            - $ref: '#/definitions/transaction'
            - $ref: '#/definitions/version'
        "404":
          description: Transaction not found
        "500":
          description: Internal server error
  /health:
    post:
      description: returns 200
      tags:
      - health
      summary: returns 200 to prove the service is alive
      operationId: healthCheck
      responses:
        "200":
          description: OK
  /transactions:
    post:
      description: Sends money from one account to another
      consumes:
      - application/json
      produces:
      - application/json
      tags:
      - transactions
      summary: Sends money from one account to another
      operationId: CreateTransaction
      parameters:
      - description: Transaction to create
        name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/newtransaction'
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/transaction'
            - $ref: '#/definitions/version'
        "400":
          description: Nice try! You can't send negative amounts...
        "500":
          description: Internal server error
definitions:
  newtransaction:
    type: object
    required:
    - sender
    - receiver
    - amount
    properties:
      amount:
        type: number
        format: currency
      receiver:
        type: integer
        format: int64
      sender:
        type: integer
        format: int64
  transaction:
    allOf:
    - type: object
      required:
      - sender
      - receiver
      - amount
      properties:
        amount:
          type: number
          format: currency
        receiver:
          type: integer
          format: int64
        sender:
          type: integer
          format: int64
    - type: object
      required:
      - id
      properties:
        id:
          type: string
  version:
    type: object
    required:
    - version
    properties:
      version:
        type: string
tags:
- description: Operations about transactions
  name: transaction-log
